spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
server.port=8081
security.jwt.secret=${JWT_SECRET}

# 15 minutes
security.jwt.access-token-expiration=900000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.rental_platform_backend=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always